### ISSUE TITLE
Screen Rotations (even when not animated) freezes app

### ISSUE THREAD

**Issue by ehlersd** [gontovnik/DGActivityIndicatorView#10]
Not quite sure why, but if the DGActivityIndicatorView:setupAnimation is called, the app will "freeze" up (not crash) when the device/screen is rotated.

If I comment out my call to DGActivityIndicatorView:setSize: (which calls setupAnimation), the app will rotate and continue functioning correctly.

**Comment by ehlersd** [comment]
It appears to be caused by this line in the setupAnimation function: `self.layer.speed = 0.0f;`

**Comment by ehlersd** [comment]
I made the following changes, and it seems to be working now.  I commented out lines, and added a single line to stopAnimation that nil's self.layer.sublayers.

Thoughts?

```
- (void)setupAnimation {
    self.layer.sublayers = nil;

    id<DGActivityIndicatorAnimationProtocol> animation = [DGActivityIndicatorView activityIndicatorAnimationForAnimationType:_type];

    if ([animation respondsToSelector:@selector(setupAnimationInLayer:withSize:tintColor:)]) {
        [animation setupAnimationInLayer:self.layer withSize:CGSizeMake(_size, _size) tintColor:_tintColor];
        //self.layer.speed = 0.0f;
    }
}

- (void)startAnimating {
    if (!self.layer.sublayers) {
        [self setupAnimation];
    }
    //self.layer.speed = 1.0f;
    _animating = YES;
}

- (void)stopAnimating {
    //self.layer.speed = 0.0f;
    self.layer.sublayers = nil;
    _animating = NO;
}

#pragma mark -
#pragma mark Setters

- (void)setType:(DGActivityIndicatorAnimationType)type {
    if (_type != type) {
        _type = type;

        //[self setupAnimation];
    }
}

- (void)setSize:(CGFloat)size {
    if (_size != size) {
        _size = size;

        //[self setupAnimation];
    }
}
```

**Comment by gontovnik** [comment]
Hm. Which version of iOS are you running on? `self.layer.speed = 0.0f;` just sets animation speed to 0, so it does not animate. When it is set to `1.0f`, it means it will animate with a normal speed.

**Comment by ehlersd** [comment]
iOS9.1

**Comment by ehlersd** [comment]
Does this layer speed also affect the animations that occur when rotating the device?  Do the animations you setup for each type also affect the layer when it animates to the new location/constraints following the rotate?

**Comment by spensko** [comment]
same issue here. 
ios 8.4 & 9.2. DGActivityIndicatorView as view with autolayout on ipad app. after rotation app freezes (not responding on any touches and even -touchesBegan not called). sending app to background and open it again fixed issue until next rotation. commenting  
`self.layer.speed =`
fixed problem at all

**Comment by timoman** [comment]
Sorry to dig up an old thread, but I just wanted to chime in and say that I'm seeing this, too.
I have several `DGActivityIndicatorView`s set up via storyboard, though I don't know if that matters.

I was personally able to get around this without modifying the source by simply calling `startAnimating` on all of my `DGActivityIndicatorView`s after setting their properties. I'm able to do that because I hide my spinners when I'm done with them, but that won't be possible for all use cases.

**Comment by gontovnik** [comment]
Cannot reproduce in 2.1.
