### ISSUE TITLE
How to use it with Autolayout?

### ISSUE THREAD

**Issue by dymx101** [gontovnik/DGActivityIndicatorView#11]
Hi,

I saw the example is using 'setFrame:' to set the layout of the indicator view, but how can I use it with AL?

**Comment by gontovnik** [comment]
Hey. What happens if you use it with auto layout now? Does it not display correctly?

**Comment by CPDigitalDarkroom** [comment]
It does not seem to work with AutoLayout.

**Comment by gontovnik** [comment]
Fixed in 35533f5c0605891f0aee3b32c03b5c9c2872eda1
