### ISSUE TITLE
Use inside uirefreshcontrol

### ISSUE THREAD

**Issue by ingscjoshua** [gontovnik/DGActivityIndicatorView#13]
Excuse me, how to implementing for uirefreshcontrol i'm like replace with this activity indicator

**Comment by gontovnik** [comment]
I think [UIRefreshControl](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIRefreshControl_class/) does not have a way to put custom loading view. What you could do is use [SVPullToRefresh](https://github.com/samvermette/SVPullToRefresh) and set a custom view. :+1:
