### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by rlaferla** [gontovnik/DGActivityIndicatorView#16]
How about a Swift version?

**Comment by ahmi** [comment]
They are not replying :(

**Comment by vitalys** [comment]
Why do you need Swift implementation of this library? You can use it in your Swift project.

**Comment by gontovnik** [comment]
I have no time to re-write it in Swift. Please feel free to do it yourself, otherwise you can just use ObjC library in Swift project as Vitaly told.

**Comment by gontovnik** [comment]
https://github.com/ninjaprox/NVActivityIndicatorView
