### ISSUE TITLE
Swift 

### ISSUE THREAD

**Issue by 0x1306a94** [gontovnik/DGActivityIndicatorView#18]
hello!  I am a beginner of the iOS, I use a Swift, translation of the library, you have a problem, the last two don't know how to remove the animation in the middle of the curve. Don't know why the Objective - c: no problem, trouble you see, what's the problem?  https://github.com/king129/SJActivityIndicatorView.git

**Comment by gontovnik** [comment]
https://github.com/ninjaprox/NVActivityIndicatorView
