### ISSUE TITLE
New release with new views

### ISSUE THREAD

**Issue by thiagorossener** [gontovnik/DGActivityIndicatorView#8]
Hi,

Could you please update CocoaPods with the new views? The current version has only 5 views, and I've been seen amazing new views I would like to try.

Actually, I will try to update my Podfile with the last commit here to test, but a new version would be great :)

Thanks, have a nice day!

**Comment by SebastianBoldt** [comment]
If you do not want to wait you can specify a commit inside your podfile like this
   ``` pod 'DGActivityIndicatorView', :git => 'https://github.com/SebastianBoldt/DGActivityIndicatorView', :commit => 'a5ef37e3669b182908e483069e752296853ade20'```

**Comment by SebastianBoldt** [comment]
+1 yes, updating the podspec would be nice.

**Comment by gontovnik** [comment]
Will do that!

**Comment by thiagorossener** [comment]
Awesome!

**Comment by SebastianBoldt** [comment]
Thx m8.

**Comment by gontovnik** [comment]
Done. :+1:  I think it takes time for Cocoapods to update it, but let me know if it does/doesn't not work for you.
