### ISSUE TITLE
Animations take time to stop

### ISSUE THREAD

**Issue by rlaferla** [gontovnik/DGActivityIndicatorView#9]
I tried stopAnimating and also hidden = YES but the animation continues on screen for a couple of seconds after being asked to stop.

**Comment by gontovnik** [comment]
Did you try to fix that?

**Comment by rlaferla** [comment]
I tried changing how it was used by app but not the activity view classes itself.  It's still a problem.  I think the animation layer might be still executing and is taking priority over "hidden".  Ideas?

I'm using: `DGActivityIndicatorAnimationTypeBallScaleMultiple`

```
DGActivityIndicatorView * sp = [[DGActivityIndicatorView alloc] initWithType:DGActivityIndicatorAnimationTypeBallScaleMultiple tintColor:[UIColor grayColor] size:150.0];
```

**Comment by benaneesh** [comment]
@rlaferla did you run it on the main thread?

**Comment by ingscjoshua** [comment]
Hello im try use in my request with AFNetworking and when  stopAnimating not dissApper it's normal ?

**Comment by gontovnik** [comment]
Hello. Are you trying to stop animation on the main thread?
